In [40]:
import itertools
import numpy as np
from numpy import linalg as LA
import math

In [41]:
# number of sites
N = 4

# constants
U = 3
t = 1

def generate_basis_states(n):
    """
    Generates basis states for half filling of N sites
    """
    result = []
    int_result = []
    for bits in itertools.combinations(range(n * 2), n):
        # only choosing N bits from N * 2 bits, so half filling
        s = ['0'] * n * 2
        for bit in bits:
            # first n bits are up, second n are down
            # sites go 0 to N - 1 for each spin
            s[bit] = '1'
        int_result.append(int(''.join(s),2)) # integer representation of bit basis
        result.append(''.join(s))            # bit (string) basis
    # order ascending
    return (result[::-1], int_result[::-1])

(result, basis_states) = generate_basis_states(N)

In [42]:
#for i in range(len(result)):
#    print('{0}\t\t|{1}>\t\t{2}'.format(i+1, result[i], basis_states[i]))

In [43]:
# setting up U term in half-filling space
h_u = np.array([[ 0 for i in range(len(result))] for j in range(len(result))])

# separate the bit basis into up (first N) and down (last N) spins
# implemented very complicated for some reason
# spins = [(bin((x >> N) & int('1'*N, 2))[2:].zfill(N), bin(x & int('1'*N, 2))[2:].zfill(N)) for x in basis_states]
#          up     down
spins = [(x[:N], x[N:]) for x in result]

for i in range(len(spins)):
    # if two particles are on the same site this is recorded in h_u. Only diagonal is affected
    # i.e. ('00', '11') --> 0*1 + 0*1 = 0
    #      ('01', '01') --> 0*0 + 1*1 = 1  both particles are on side 1
    s = sum([int(spins[i][0][j]) * int(spins[i][1][j]) for j in range(N)])
    if (s > 0):
        #print(result[i] + ' has', s, 'doubly occupied sites')
        h_u[i][i] = s

# U_1 is state 0101 [1][1]  
# h_u[1][1] = 0

# multiply by U
h_u *= U
print()
print(h_u)


[[0 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 0]]


In [44]:
# epsilon term. Only apply when N = 2?
# this depends on the ordering of the sites
# |site 0 up, site 1 up, site 0 down, site 1 down>

e0 = 0
e1 = 0
if (N == 2 and e1 != 0):
    h_e0 = np.array([[ 0 for i in range(len(result))] for j in range(len(result))])
    h_e1 = np.array([[ 0 for i in range(len(result))] for j in range(len(result))])
    for i in range(len(result)):
        # count the number of particles on site one/zero
        for j in range(N):
            h_e0[i][i] += int(result[i][2*j])
            h_e1[i][i] += int(result[i][2*j+1])
    h_e0 *= e0
    h_e1 *= e1
    h_u += (h_e1 + h_e0)
    print(h_u)

In [45]:
def hop(state):
    def ns(s):
        """
        Finds the possible neighbor states for a state s. Spins can't flip while hopping
        """
        hops = []
        for i in range(len(s)):
            if(s[i] == '1'):
                temp = list(s)
                # see if it can hop one site forward (with periodic bounding conditions)
                # can only hop if final site is unoccupied
                if (i + 1 == len(s)):
                    # hopping from site n - 1 to 0
                    if (s[0] == '0'):
                        temp[i] = '0'
                        temp[0] = '1'
                        # counting number of particles to hop through
                        if ((-1)**temp[1:-1].count('1') == 1):
                            hops.append(''.join(temp))
                        else: 
                            hops.append('-' + ''.join(temp))
                        temp = list(s)
                else:
                    # hopping one site ahead
                    if (s[i + 1] == '0'):
                        temp[i] = '0'
                        temp[i + 1] = '1'
                        hops.append(''.join(temp))
                        temp = list(s)
                if (i - 1 < 0):
                    # hopping from site 0 to n - 1
                    if (s[-1] == '0'):
                        temp[i] = '0'
                        temp[-1] = '1'
                        # counting number of particles to hop through
                        if ((-1)**temp[1:-1].count('1') == 1):
                            hops.append(''.join(temp))
                        else: 
                            hops.append('-' + ''.join(temp))
                        temp = list(s)
                else:
                    # hopping one site backwards
                    if (s[i - 1] == '0'):
                        temp[i] = '0'
                        temp[i - 1] = '1'
                        hops.append(''.join(temp))
                        temp = list(s)
        return hops
    
    neighbor_states = []
    # find possible hops for particles with up spin
    up_hops = list(dict.fromkeys(ns(state[0])))
    # find possible hops for particles with down spin
    down_hops = list(dict.fromkeys(ns(state[1])))

    for i in range(len(down_hops)):
        if (down_hops[i][0] == '-'):
            hop = basis_states.index(int(state[0] + down_hops[i][1:], 2))
            if (hop == 0):
                neighbor_states.append(-0.0)
            else:
                neighbor_states.append(-1 * hop)
        else:
            neighbor_states.append(basis_states.index(int(state[0] + down_hops[i], 2)))
    for i in range(len(up_hops)):
        if (up_hops[i][0] == '-'):
            hop = basis_states.index(int(up_hops[i][1:] + state[1], 2))
            if (hop == 0):
                neighbor_states.append(-0.0)
            else:
                neighbor_states.append(-1 * hop)
        else:
            neighbor_states.append(basis_states.index(int(up_hops[i] + state[1], 2)))
    
    return neighbor_states

# setting up t term in half-filling space
h_t = np.array([[ 0 for i in range(len(result))] for j in range(len(result))])


for i in range(len(spins)):
    ns = hop(spins[i])
    #print('state', i, '(', result[i], ') neighbor states', ns)
    for j in range(len(ns)):
        if (math.copysign(1, ns[j]) == -1.0):
            h_t[i][abs(int(ns[j]))] = -1
        else:
            h_t[i][ns[j]] = 1
# multiply by -t
h_t *= -t
print()
print(h_t)



[[ 0  0  0 ...  0  0  0]
 [ 0  0 -1 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0 -1  0]
 [ 0  0  0 ... -1  0  0]
 [ 0  0  0 ...  0  0  0]]


In [46]:
h = h_u + h_t
#np.savetxt('h.txt', h, '%-2d', ', ')
print(h)

[[ 0  0  0 ...  0  0  0]
 [ 0  3 -1 ...  0  0  0]
 [ 0 -1  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  3 -1  0]
 [ 0  0  0 ... -1  3  0]
 [ 0  0  0 ...  0  0  0]]


In [47]:
np.count_nonzero(h)

374

In [48]:
w, v = LA.eigh(h)
print(w)

[-2.42442890e+00 -2.19148250e+00 -2.19148250e+00 -2.19148250e+00
 -1.42442890e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -5.08956082e-01
  0.00000000e+00  0.00000000e+00  2.76962997e-16  1.10273682e-15
  1.16150763e-15  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.68252642e+00  1.68252642e+00  1.68252642e+00
  2.00000000e+00  2.00000000e+00  2.00000000e+00  3.00000000e+00
  3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
  3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
  3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
  3.00000000e+00  4.00000000e+00  4.00000000e+00  4.00000000e+00
  4.00000000e+00  4.00000000e+00  4.00000000e+00  4.00000000e+00
  4.31747358e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
  5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
  5.00000000e+00  6.00000

In [49]:
gsEigen = np.array(result)[abs(v[:,0]) > 0]
hf = []
for i in range(len(gsEigen)):
    for j in range(N):
        if (int(gsEigen[i][j]) & int(gsEigen[i][j+N])):
            hf.append(gsEigen[i])
len(hf)

57

In [50]:
def creation(state, site, spin):
    """
    Creates a particle at site 'site' with spin 'spin', if possible
    |0011> has sites 0, 1, in that order per N sites
    param spin: 1 - up, 0 - down
    """
    state = list(state)
    #             up                    down
    particle = state[:N] if spin else state[N:]
    if (particle[site] == '1'):
        # Can't add a particle to an already filled site, return vacuum state
        return ''
    else:
        particle[site] = '1'
        if (spin):
            state[:N] = particle
        else:
            state[N:] = particle
        return state

def annihilation(state, site, spin):
    """
    Annihilates a particle at site 'site' with spin 'spin', if possible
    |0011> has sites 0, 1, in that order per N sites
    param spin: 1 - up, 0 - down
    """
    state = list(state)
    #             up                    down
    particle = state[:N] if spin else state[N:]

    if (particle[site] == '0'):
        # State has been destroyed, so return vacuum state
        return ''
    else:
        particle[site] = '0'
        if (spin):
            state[:N] = particle
        else:
            state[N:] = particle
        return state


In [51]:
# Building the single particle density matrix
# 1 for up, 0 for down
# sigma1, sigma2 up to N. i, j sites

spdm = {}

for sigma1 in range(2):
    for i in range(N):        
        for sigma2 in range(2):
            for j in range(N):
                # setting up M(i, j, sigma1, sigma2)
                arr = np.array([[ 0 for i in range(len(result))] for j in range(len(result))])
                
                for mu in range(len(result)):
                    for nu in range(len(result)):
                        # < nu | a_{i, sigma1}^dagger a_{j, sigma2} | mu >
                
                        phi1 = annihilation(result[nu], i, sigma1)
                        phi2 = annihilation(result[mu], j, sigma2)
                        if ((phi1 != '' and phi2 != '') and phi1 == phi2):
                            arr[mu][nu] = 1
                spdm[str(i)+str(sigma1)+str(j)+str(sigma2)] = arr

In [52]:
almost_spdm_arr = np.array([0.0 for i in range(len(spdm))])
for i, j in enumerate(spdm.values()):
    almost_spdm_arr[i] = np.dot(v[:, 0].conj().T, np.dot(j, v[:, 0]))
asa = np.reshape(almost_spdm_arr, (2*N,2*N))
print(np.around(asa, decimals=2))
print(np.trace(asa))

[[ 0.5   0.22 -0.   -0.22 -0.   -0.   -0.    0.  ]
 [ 0.22  0.5   0.22 -0.   -0.   -0.   -0.    0.  ]
 [-0.    0.22  0.5   0.22 -0.   -0.   -0.    0.  ]
 [-0.22 -0.    0.22  0.5   0.    0.    0.    0.  ]
 [-0.   -0.   -0.    0.    0.5   0.22 -0.   -0.22]
 [-0.   -0.   -0.    0.    0.22  0.5   0.22  0.  ]
 [-0.   -0.   -0.    0.   -0.    0.22  0.5   0.22]
 [ 0.    0.    0.    0.   -0.22  0.    0.22  0.5 ]]
3.999999999999999
